# Generated by Django 4.1.4 on 2022-12-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='university_end_date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='university_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='university_specialization',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='university_start_date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='work_end_date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='work_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='work_projects',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='work_specialization',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='work_start_date',
        ),
        migrations.AddField(
            model_name='resume',
            name='about_education',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='about_me',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='about_work_expirience',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='age',
            field=models.IntegerField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='surname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_name',
            field=models.CharField(max_length=50),
        ),
    ]
